name: Builder
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Directory
        run: |
          echo "Folgers in your cup."
          ls -la
          cd .. && ls -la
          cd .. && ls -la
          cd .. && ls -la
#          mkdir images && sudo PATH=./node_modules/.bin:$PATH ../../builder --noninteractive && touch ../images/.gitkeep
